export const programsData = [
  {
    programKodu: "106510098",
    universiteTuru: "DEVLET",
    universiteAdi: "ABDULLAH GÜL ÜNİVERSİTESİ (KAYSERİ)",
    fakulteAdi: "İNSAN VE TOPLUM BİLİMLERİ FAKÜLTESİ",
    programAdi: "Psikoloji (İngilizce)",
    puanTuru: "EA",
    genelKontenjan: 40,
    enKucukPuan: "391.38245",
    enBuyukPuan: "425.10258",
  },
  {
    programKodu: "106510085",
    universiteTuru: "DEVLET",
    universiteAdi: "ABDULLAH GÜL ÜNİVERSİTESİ (KAYSERİ)",
    fakulteAdi: "İNSAN VE TOPLUM BİLİMLERİ FAKÜLTESİ",
    programAdi: "Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce)",
    puanTuru: "EA",
    genelKontenjan: 55,
    enKucukPuan: "354.01811",
    enBuyukPuan: "450.46407",
  },
  {
    programKodu: "106510014",
    universiteTuru: "DEVLET",
    universiteAdi: "ABDULLAH GÜL ÜNİVERSİTESİ (KAYSERİ)",
    fakulteAdi: "MİMARLIK FAKÜLTESİ",
    programAdi: "Mimarlık (İngilizce)",
    puanTuru: "SAY",
    genelKontenjan: 40,
    enKucukPuan: "379.00664",
    enBuyukPuan: "449.69508",
  },
  {
    programKodu: "106510021",
    universiteTuru: "DEVLET",
    universiteAdi: "ABDULLAH GÜL ÜNİVERSİTESİ (KAYSERİ)",
    fakulteAdi: "MÜHENDİSLİK FAKÜLTESİ",
    programAdi: "Bilgisayar Mühendisliği (İngilizce)",
    puanTuru: "SAY",
    genelKontenjan: 80,
    enKucukPuan: "482.22722",
    enBuyukPuan: "492.68168",
  },
  {
    programKodu: "101110011",
    universiteTuru: "DEVLET",
    universiteAdi: "ANKARA ÜNİVERSİTESİ",
    fakulteAdi: "HUKUK FAKÜLTESİ",
    programAdi: "Hukuk",
    puanTuru: "EA",
    genelKontenjan: 750,
    enKucukPuan: "445.51234",
    enBuyukPuan: "498.12456",
  },
  {
    programKodu: "202510015",
    universiteTuru: "VAKIF",
    universiteAdi: "BİLKENT ÜNİVERSİTESİ (ANKARA)",
    fakulteAdi: "MÜHENDİSLİK FAKÜLTESİ",
    programAdi: "Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)",
    puanTuru: "SAY",
    genelKontenjan: 45,
    enKucukPuan: "525.10543",
    enBuyukPuan: "545.98765",
  },
  {
    programKodu: "102210045",
    universiteTuru: "DEVLET",
    universiteAdi: "BOĞAZİÇİ ÜNİVERSİTESİ (İSTANBUL)",
    fakulteAdi: "İKTİSADİ VE İDARİ BİLİMLER FAKÜLTESİ",
    programAdi: "İşletme (İngilizce)",
    puanTuru: "EA",
    genelKontenjan: 85,
    enKucukPuan: "490.87564",
    enBuyukPuan: "515.23412",
  },
  {
    programKodu: "105610023",
    universiteTuru: "DEVLET",
    universiteAdi: "İSTANBUL ÜNİVERSİTESİ",
    fakulteAdi: "İLETİŞİM FAKÜLTESİ",
    programAdi: "Halkla İlişkiler ve Tanıtım",
    puanTuru: "SÖZ",
    genelKontenjan: 120,
    enKucukPuan: "385.12345",
    enBuyukPuan: "420.98765",
  }
];
